apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet-0404-master
  janus-idp.io/tekton: dotnet-0404-master
  backstage.io/kubernetes-id: dotnet-0404-master
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-0404-master
resources: 
- deployment.yaml
- route.yaml
- service.yaml
